// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABGjBrLDN3JjoVrvM_5HrxDqqJ7blRKoQ',
    appId: '1:1038740925956:android:d2a3450376ed0c27424f51',
    messagingSenderId: '1038740925956',
    projectId: 'telechat---chatapp',
    storageBucket: 'telechat---chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKfToV4oZRpuow3BKF0b6jjmdIOtb2OHc',
    appId: '1:1038740925956:ios:54ce1db79a7d67b9424f51',
    messagingSenderId: '1038740925956',
    projectId: 'telechat---chatapp',
    storageBucket: 'telechat---chatapp.firebasestorage.app',
    androidClientId: '1038740925956-s2sp1go4oloc3nej6jj6729t3673o3k9.apps.googleusercontent.com',
    iosClientId: '1038740925956-q10gm05m7blr2im49ikejeq81t888o2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.telechat',
  );

}